const SET_ROLE = "SET_ROLE"
const REMOVE_ROLE = "REMOVE_ROLE"
const REMOVE_TOKEN = "REMOVE_TOKEN"
const SET_USERINFO = "SET_USERINFO"
const SET_ADMININFO = "SET_ADMININFO"
const SET_SUPERADMININFO = "SET_SUPERADMININFO"

export {
  SET_ROLE,
  REMOVE_ROLE,
  REMOVE_TOKEN,
  SET_USERINFO,
  SET_ADMININFO,
  SET_SUPERADMININFO
}
